version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: web-postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: graphdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: graphdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      FLASK_SECRET_KEY: your_super_secret_key
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
    depends_on:
      - postgres
    volumes:
      - ./web:/app

  mcp_server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: mcp_server
    restart: always
    ports:
      - "8081:8080" 
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      INSTAVIBE_BASE_URL: http://web:8080/api 
    depends_on:
      - web
    volumes:
      - ./mcp_server:/app

  platform_mcp_client:
    build:
      context: .
      dockerfile: ./agents/platform_mcp_client/Dockerfile 
    container_name: mcp-client-agent
    restart: always
    ports:
      - "10002:10002"
    environment:
      MCP_SERVER_URL: "http://mcp_server:8080/sse" 
      A2A_SERVER_HOST: "0.0.0.0" 
      A2A_SERVER_PORT: "10002" 
      APP_PORT: "10002" 
      PUBLIC_URL: "http://platform-mcp-client-agent:10002" 
    depends_on:
      - mcp_server
      - web 
    volumes:
      - ./agents:/app/agents

  adk_platform:
    build:
      context: . 
      dockerfile: Dockerfile.adk_web 
    container_name: adk-platform
    restart: always
    ports:
      - "8000:8000"
    environment:
      ADK_AGENT_URL: "http://platform-mcp-client-agent:10002"
      PYTHONPATH: "/app" 
      ADK_APP_NAME: "platform_mcp_client" 
    volumes:
      - ./agents:/app 
    depends_on:
      - platform_mcp_client 

volumes:
  postgres_data: